# Generated by Django 4.2.4 on 2023-08-12 13:40

from django.db import migrations, models

#TODO django.db.utils.ProgrammingError: column "profile_picture" of relation "accounts_appuser" already exists


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='profile_picture',
            field=models.URLField(blank=True, max_length=2083, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='last name'),
        ),
    ]
